site_name: iBank Documentation
site_description: Dokumentasi aplikasi core banking iBank
site_url: https://wisnu.github.io/ibank-docs/

theme:
  name: material
  custom_dir: overrides
  language: id
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy

nav:
  - Home: index.md

  - iBank:
      - General Ledger:
          - TSD Architecture: ibank/GL/TSD Architecture.md
          - Chart of Account:
              - PRD - Chart of Account: ibank/GL/chart-of-account/PRD_COA_Main.md
              - FSD - Chart of Account: ibank/GL/chart-of-account/FSD_COA_Main.md
              - COA List:
                  - FSD - COA List: ibank/GL/chart-of-account/list/FSD_COA_List.md
              - COA Create:
                  - FSD - COA Create: ibank/GL/chart-of-account/create/FSD_COA_Create.md
              - COA Edit:
                  - FSD - COA Edit: ibank/GL/chart-of-account/edit/FSD_COA_Edit.md
                  - TSD - COA Edit: ibank/GL/chart-of-account/edit/TSD_COA_Edit.md
                  - TEST - COA Edit: ibank/GL/chart-of-account/edit/TEST_COA_Edit.md
                  - Referensi: ibank/GL/chart-of-account/edit/referensi.md
          - Neraca / Laba Rugi:
              - FSD - Neraca / Laba Rugi: ibank/GL/balance-sheet/FSD_balance-sheet_report.md
              - TSD - Neraca / Laba Rugi: ibank/GL/balance-sheet/TSD_balance-sheet_report.md
          - Trial Balance:
              - FSD - Trial Balance: ibank/GL/trial-balance/FSD_trial-balance_report.md
              - TSD - Trial Balance: ibank/GL/trial-balance/TSD_trial-balance_report.md
          - Buku Besar:
              - Coming Soon: ibank/GL/ledger/placeholder.md

  - BJBS:
      - Fingerscan:
          - FSD - Fingerscan Biometrik: bjbs/Fingerscan/FSD_Fingerscan_Biometrik.md

  - BCAS:
      - Enhance Dormant:
          - Design Plan: bcas/enhance_dormant/dormant_design_plan.md
          - Use Case: bcas/enhance_dormant/dormant_use_case.md
          - Screenshot Checklist: bcas/enhance_dormant/dormant_screenshot.md
      - Saku Valas:
          - FSD - Saku Valas: bcas/saku_valas/fsd_sakuvalas.md

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight
  - pymdownx.details
  - admonition
  - pymdownx.tabbed:
      alternate_style: true

extra_javascript:
  - https://unpkg.com/mermaid@10/dist/mermaid.min.js
