site_name: iBank Documentation
site_description: Dokumentasi aplikasi core banking iBank
site_url: https://github.com/wishnew/ibank-docs

theme:
  name: material
  language: id
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy

nav:
  - Home: index.md

  - General Ledger:
      - Chart of Account:
          - PRD: GL/chart-of-account/PRD_COA_Main.md
          - FSD: GL/chart-of-account/FSD_COA_Main.md
          - List:
              - FSD: GL/chart-of-account/list/FSD_COA_List.md
          - Create:
              - FSD: GL/chart-of-account/create/FSD_COA_Create.md
          - Edit:
              - FSD: GL/chart-of-account/edit/FSD_COA_Edit.md
              - TSD: GL/chart-of-account/edit/TSD_COA_Edit.md
              - TEST: GL/chart-of-account/edit/TEST_COA_Edit.md

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight
  - pymdownx.details
  - admonition
  - pymdownx.tabbed:
      alternate_style: true

extra_javascript:
  - https://unpkg.com/mermaid@10/dist/mermaid.min.js
