
CREATE TABLE ibcore.rekeningaktivitasnonfin (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nomor_rekening      VARCHAR(20)   NOT NULL,
    tanggal_aktivitas   TIMESTAMP     NOT NULL,
    kode_aktivitas      VARCHAR(20)   NOT NULL,  -- CEK_SALDO | CEK_MUTASI | LOGIN_MB | LOGIN_IB | LOGIN_ATM
    kode_channel        VARCHAR(10)   NULL,       -- ATM | MOBILE | IB | TELLER | API
    nomor_referensi     VARCHAR(50)   NULL,
    user_input          VARCHAR(20)   NULL,
    terminal_input      VARCHAR(19)   NULL,
    kode_cabang         VARCHAR(10)   NULL,
    tanggal_input       TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT rekeningaktivitasnonfin_pkey PRIMARY KEY (id)
);

-- Index per rekening + tanggal (query audit)
CREATE INDEX idx_ran_norek_tgl
    ON ibcore.rekeningaktivitasnonfin
    (nomor_rekening, tanggal_aktivitas DESC);

-- Index untuk monitoring per jenis/kode_channel
CREATE INDEX idx_ran_jenis
    ON ibcore.rekeningaktivitasnonfin
    (kode_aktivitas, tanggal_aktivitas);

-- Index untuk purge / archival berkala
CREATE INDEX idx_ran_tglakt
    ON ibcore.rekeningaktivitasnonfin
    (tanggal_aktivitas);

-- tambah kolom rekeningliabilitas
ALTER TABLE ibcore.rekeningliabilitas
    ADD COLUMN tgl_aktivitas_terakhir TIMESTAMP NULL;

ALTER TABLE ibcore.rekeningliabilitas
    ADD COLUMN tgl_aktivitas_nonfin_terakhir TIMESTAMP NULL;


-- tambah table temporary candidate tgl transaksi terakhir
CREATE TABLE ibtmp.rekening_transaksi_terakhir (
    nomor_rekening      VARCHAR(20)  NOT NULL,
    tanggal_transaksi   TIMESTAMP    NOT NULL,
    CONSTRAINT rekening_transaksi_terakhir_pkey PRIMARY KEY (nomor_rekening)
);

-- tambah table temporary candidate tgl aktivitas terakhir
CREATE TABLE ibtmp.rekening_aktivitas_nonfin_terakhir (
    nomor_rekening      VARCHAR(20)  NOT NULL,
    tanggal_aktivitas   TIMESTAMP    NOT NULL,
    CONSTRAINT rekening_aktivitas_terakhir_pkey PRIMARY KEY (nomor_rekening)
);


-- Update table report rekening dormant
ALTER TABLE ibrep.rekening_dorman
    ADD COLUMN tgl_aktivitas_terakhir TIMESTAMP NULL;

DROP TABLE IF EXISTS ibrep.rekening_tidak_aktif;

-- Update table report rekening tidak aktif
CREATE TABLE ibrep.rekening_tidak_aktif (
    id_report              INTEGER         NOT NULL,
    nomor_rekening         VARCHAR(20)     NOT NULL,
    tanggal_proses         DATE            NOT NULL,
    tgl_aktivitas_terakhir TIMESTAMP       NULL,
    param_hari_tidak_aktif integer         NULL,
    saldo                  NUMERIC(36, 10) NULL,

    CONSTRAINT rekening_tidak_aktif_pkey PRIMARY KEY (id_report)
);

CREATE SEQUENCE ibrep.seq_rekening_tidak_aktif
    START WITH 1 INCREMENT BY 1 NO MAXVALUE NO CYCLE CACHE 20;

CREATE INDEX idx_rep_tdkakt_norek ON ibrep.rekening_tidak_aktif
    (nomor_rekening, tanggal_proses DESC);

ALTER TABLE ibcore.parameterglobal
    ADD COLUMN kode_group VARCHAR(30) NULL;

INSERT INTO ibcore.parameterglobal (kode_parameter, tipe_parameter, nilai_parameter, deskripsi, is_parameter_system, kode_group)
    VALUES ('TAKT_HARI',      'N', 360,   'Hari default jadi tidak aktif',       'F', 'REKENING_DORMANT');
INSERT INTO ibcore.parameterglobal (kode_parameter, tipe_parameter, nilai_parameter, deskripsi, is_parameter_system, kode_group)
    VALUES ('DORM_HARI',      'N', 1800,  'Hari default jadi dormant',           'F', 'REKENING_DORMANT');
INSERT INTO ibcore.parameterglobal (kode_parameter, tipe_parameter, nilai_parameter, deskripsi, is_parameter_system, kode_group)
    VALUES ('TUTUP_NOL_HARI', 'N', 180,   'Hari default tutup otomatis dormant', 'F', 'REKENING_DORMANT');
INSERT INTO ibcore.parameterglobal (kode_parameter, tipe_parameter, nilai_parameter, deskripsi, is_parameter_system, kode_group)
    VALUES ('TAKT_BIAYA',     'N', 0,     'Biaya default rekening tidak aktif',  'F', 'REKENING_DORMANT');
INSERT INTO ibcore.parameterglobal (kode_parameter, tipe_parameter, nilai_parameter, deskripsi, is_parameter_system, kode_group)
    VALUES ('DORM_BIAYA',     'N', 10000, 'Biaya default rekening dormant',      'F', 'REKENING_DORMANT');


ALTER TABLE ibcore.produk
    ADD COLUMN is_custom_tidak_aktif         VARCHAR(1),
    ADD COLUMN is_custom_dormant             VARCHAR(1),
    ADD COLUMN is_custom_tutup_oto           VARCHAR(1),
    ADD COLUMN jumlah_hari_jadi_dormant      integer,
    ADD COLUMN biaya_rekening_tidak_aktif    NUMERIC(20, 8),
    ADD COLUMN is_biaya_rekening_tidak_aktif VARCHAR(1),
    ADD COLUMN is_exc_tidakaktif             VARCHAR(1),
    ADD COLUMN is_exc_tutupnol               VARCHAR(1);

ALTER TABLE ibcore.rekeningliabilitas
    ADD COLUMN is_biaya_rekening_tidakaktif VARCHAR(1);

CREATE TABLE ibtmp.autoclose_zerobalance_candidate
(
    nomor_rekening      VARCHAR(20)     PRIMARY KEY,
    kode_cabang         VARCHAR(20),
    kode_valuta         VARCHAR(10),
    kode_produk         VARCHAR(10),
    param_hari_tutup_oto integer,
    tgl_saldo_nol       TIMESTAMP,
    saldo               NUMERIC(38, 8)
);

CREATE INDEX idx_autoclose_cand_norek ON ibtmp.autoclose_zerobalance_candidate (nomor_rekening);
CREATE INDEX idx_autoclose_cand_tgl   ON ibtmp.autoclose_zerobalance_candidate (tgl_saldo_nol);

CREATE TABLE ibtmp.rekening_dorman_candidate
(
    nomor_rekening          VARCHAR(20)     NOT NULL,
    saldo                   NUMERIC(36, 10),
    tgl_aktivitas_terakhir  TIMESTAMP,
    kode_produk             VARCHAR(10),
    param_hari_dormant      integer,
    process_status          integer,
    PRIMARY KEY (nomor_rekening)
);
 
CREATE TABLE ibtmp.rekening_tidak_aktif_candidate
(
    nomor_rekening          VARCHAR(20)     NOT NULL,
    saldo                   NUMERIC(36, 10),
    tgl_aktivitas_terakhir  TIMESTAMP,
    kode_produk             VARCHAR(10),
    param_hari_tidak_aktif  integer,
    process_status          integer,
    PRIMARY KEY (nomor_rekening)
);

alter table ibrep.rekening_tutupotomatis add column tgl_saldo_nol timestamp;

alter table ibrep.rekening_tutupotomatis add column param_hari_tutup_oto integer;

INSERT INTO ibcore.report (kode_report, nama_report, template_name, script_name, tag_report, is_eod_execute, recipient, retensi, is_show_bds)
VALUES ('R041', 'Laporan Rekening Aktif jadi Tidak Aktif', 'tplRekeningTidakAktifOtomatis', 'rekening_tidakaktif_otomatis', 'GENERAL', 'F', 'C', '1B/6B/12B', NULL);

INSERT INTO ibcore.reportgroupaccess (accessid, id_peran, kode_report, accessflag)
SELECT nextval('ibcore.seq_reportgroupaccess'), id_peran, 'R041', accessflag
FROM ibcore.reportgroupaccess WHERE kode_report = 'R029';

ALTER TABLE ibrep.rekening_tidak_aktif
    ADD COLUMN param_hari_tidak_aktif NUMERIC;

INSERT INTO ibcore.enum_int (enum_name, enum_value, enum_description) VALUES ('eStatusRekening', 7, 'Tidak Aktif');

UPDATE ibcore.enum_int SET enum_description = 'Dormant' WHERE enum_name = 'eStatusRekening' AND enum_value = 2;

-- enhance parametertransaksiumum
-- Rename is_exclude_aktivitas_nasabah → tipe_exclude_aktivitas_nasabah (boolean → multi-value)
-- Tambah is_transaksi_sistem, allow_rekening_tidak_aktif, allow_rekening_dormant
-- tipe_exclude_aktivitas_nasabah, default 'F' ('F' = hitung sebagai aktivitas nasabah, 'DC' = exclude dari aktivitas nasabah, 'D' = exclude debit, 'C' = exclude kredit)
-- is_transaksi_sistem ('T'/'F'), default 'F' (untuk menandai transaksi yang memang berasal dari sistem, misal posting bunga, sehingga bisa diabaikan untuk logika tertentu seperti auto-dormant)
-- allow_rekening_tidak_aktif ('DC'/'D'/'C'/'F') , default 'F' (untuk transaksi yang diperbolehkan untuk rekening tidak aktif, DC = Boleh Debet/Kredit, D = Hanya Debet, C = Hanya Kredit, F = Tidak boleh Debet/Kredit)
-- allow_rekening_dormant ('DC'/'D'/'C'/'F'), default 'F' (untuk transaksi yang diperbolehkan untuk rekening dormant, DC = Boleh Debet/Kredit, D = Hanya Debet, C = Hanya Kredit, F = Tidak boleh Debet/Kredit)
-- rule tambahan , jika kode transaksi tidak terdapat di parameter ini, maka secara default dianggap sebagai aktivitas nasabah (tipe_exclude_aktivitas_nasabah = 'F'), bukan transaksi sistem, dan tidak boleh untuk rekening tidak aktif maupun dormant.

ALTER TABLE ibcore.parametertransaksiumum
    ADD COLUMN tipe_exclude_aktivitas_nasabah VARCHAR(2) DEFAULT 'F';

-- Migrasi nilai lama: 'T' (exclude semua) → 'DC', 'F' tetap 'F'
UPDATE ibcore.parametertransaksiumum
SET tipe_exclude_aktivitas_nasabah = 'DC'
WHERE kode_transaksi IN ('SD', 'PD', 'SC', 'SCD', 'SDP', 'SDZ', 'SI');

ALTER TABLE ibcore.parametertransaksiumum
    ADD COLUMN is_transaksi_sistem VARCHAR(1) DEFAULT 'F';

-- Transaksi sistem yang sudah diketahui (sama dengan yang di-exclude aktivitas)
UPDATE ibcore.parametertransaksiumum
SET is_transaksi_sistem = 'T'
WHERE kode_transaksi IN ('SD', 'PD', 'SC', 'SCD', 'SDP', 'SDZ', 'SI');

ALTER TABLE ibcore.parametertransaksiumum
    ADD COLUMN allow_rekening_tidak_aktif VARCHAR(2) DEFAULT 'F';

ALTER TABLE ibcore.parametertransaksiumum
    ADD COLUMN allow_rekening_dormant VARCHAR(2) DEFAULT 'F';

-- Enum values untuk eTipeExcludeAktivitas
DELETE FROM ibcore.enum_varchar WHERE enum_name = 'eTipeExcludeAktivitas';
INSERT INTO ibcore.enum_varchar (enum_name, enum_value, enum_description) VALUES ('eTipeExcludeAktivitas', 'F',  'Hitung sebagai aktivitas nasabah');
INSERT INTO ibcore.enum_varchar (enum_name, enum_value, enum_description) VALUES ('eTipeExcludeAktivitas', 'DC', 'Exclude dari aktivitas nasabah');
INSERT INTO ibcore.enum_varchar (enum_name, enum_value, enum_description) VALUES ('eTipeExcludeAktivitas', 'D',  'Exclude debit');
INSERT INTO ibcore.enum_varchar (enum_name, enum_value, enum_description) VALUES ('eTipeExcludeAktivitas', 'C',  'Exclude kredit');

-- Enum values untuk eParamAllowTrx
DELETE FROM ibcore.enum_varchar WHERE enum_name = 'eParamAllowTrx';
INSERT INTO ibcore.enum_varchar (enum_name, enum_value, enum_description) VALUES ('eParamAllowTrx', 'F',  'Tolak Debet/Kredit');
INSERT INTO ibcore.enum_varchar (enum_name, enum_value, enum_description) VALUES ('eParamAllowTrx', 'DC', 'Izinkan Debet/Kredit');
INSERT INTO ibcore.enum_varchar (enum_name, enum_value, enum_description) VALUES ('eParamAllowTrx', 'D',  'Hanya Debet');
INSERT INTO ibcore.enum_varchar (enum_name, enum_value, enum_description) VALUES ('eParamAllowTrx', 'C',  'Hanya Kredit');

UPDATE ibcore.parametertransaksiumum
SET allow_rekening_dormant = 'DC'
WHERE kode_transaksi IN ('SD', 'PD', 'SC', 'SCD', 'SDP', 'SDZ', 'SI');

update ibcore.produk 
set is_custom_dormant = 'F', is_custom_tutup_oto='F', is_exc_tutupnol='F';

-- One-time migration

-- [MIGRASI 1/3] Update tgl_transaksi_terakhir dari histtransaksi + histdetiltransaksi
-- Mengambil MAX tanggal_transaksi per rekening dari data historis,
-- mengecualikan transaksi sistem EOD yang bukan aktivitas nasabah (tipe_exclude_aktivitas_nasabah = 'DC').
-- Nilai 'F'/'D'/'C'/NULL tetap dihitung sebagai aktivitas nasabah (fail-safe default).
-- Menggunakan GREATEST agar tidak menimpa nilai yang sudah lebih baru.
UPDATE ibcore.rekeningliabilitas rl
SET tgl_transaksi_terakhir = GREATEST(
    COALESCE(rl.tgl_transaksi_terakhir, '1900-01-01'::TIMESTAMP),
    (
        SELECT MAX(t.tanggal_transaksi)
        FROM   ibcore.histdetiltransaksi d
               INNER JOIN ibcore.histtransaksi t
                       ON t.id_transaksi = d.id_transaksi
               LEFT  JOIN ibcore.parametertransaksiumum ptu
                       ON ptu.kode_transaksi = t.kode_transaksi
        WHERE  d.nomor_rekening = rl.nomor_rekening
          AND  t.status_otorisasi = 1
          AND  COALESCE(t.is_reversed, 'F') = 'F'
          AND  COALESCE(ptu.tipe_exclude_aktivitas_nasabah, 'F') != 'DC'
    )
)
WHERE EXISTS (
    SELECT 1
    FROM   ibcore.histdetiltransaksi d
           INNER JOIN ibcore.histtransaksi t
                   ON t.id_transaksi = d.id_transaksi
           LEFT  JOIN ibcore.parametertransaksiumum ptu
                   ON ptu.kode_transaksi = t.kode_transaksi
    WHERE  d.nomor_rekening = rl.nomor_rekening
      AND  t.status_otorisasi = 1
      AND  COALESCE(t.is_reversed, 'F') = 'F'
      AND  COALESCE(ptu.tipe_exclude_aktivitas_nasabah, 'F') != 'DC'
);

-- [MIGRASI 2/3] Update tgl_transaksi_terakhir dari transaksi + detiltransaksi (data H+0)
-- Menangkap transaksi yang belum dipindahkan ke hist (hari berjalan saat migrasi dijalankan).
-- Mengecualikan transaksi sistem EOD yang bukan aktivitas nasabah (tipe_exclude_aktivitas_nasabah = 'DC').
-- Nilai 'F'/'D'/'C'/NULL tetap dihitung sebagai aktivitas nasabah (fail-safe default).
UPDATE ibcore.rekeningliabilitas rl
SET tgl_transaksi_terakhir = GREATEST(
    COALESCE(rl.tgl_transaksi_terakhir, '1900-01-01'::TIMESTAMP),
    (
        SELECT MAX(t.tanggal_transaksi)
        FROM   ibcore.detiltransaksi d
               INNER JOIN ibcore.transaksi t
                       ON t.id_transaksi = d.id_transaksi
               LEFT  JOIN ibcore.parametertransaksiumum ptu
                       ON ptu.kode_transaksi = t.kode_transaksi
        WHERE  d.nomor_rekening = rl.nomor_rekening
          AND  t.status_otorisasi = 1
          AND  COALESCE(t.is_reversed, 'F') = 'F'
          AND  COALESCE(ptu.tipe_exclude_aktivitas_nasabah, 'F') != 'DC'
    )
)
WHERE EXISTS (
    SELECT 1
    FROM   ibcore.detiltransaksi d
           INNER JOIN ibcore.transaksi t
                   ON t.id_transaksi = d.id_transaksi
           LEFT  JOIN ibcore.parametertransaksiumum ptu
                   ON ptu.kode_transaksi = t.kode_transaksi
    WHERE  d.nomor_rekening = rl.nomor_rekening
      AND  t.status_otorisasi = 1
      AND  COALESCE(t.is_reversed, 'F') = 'F'
      AND  COALESCE(ptu.tipe_exclude_aktivitas_nasabah, 'F') != 'DC'
);

-- [MIGRASI 3/3] Salin tgl_transaksi_terakhir ke tgl_aktivitas_terakhir sebagai baseline awal
UPDATE ibcore.rekeningliabilitas
SET tgl_aktivitas_terakhir = tgl_transaksi_terakhir
WHERE tgl_transaksi_terakhir IS NOT NULL;
