
CREATE TABLE ibankcore.rekeningaktivitasnonfin (
    id                  NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nomor_rekening      VARCHAR2(20)  NOT NULL,
    tanggal_aktivitas   TIMESTAMP     NOT NULL,
    kode_aktivitas      VARCHAR2(20)  NOT NULL,  -- CEK_SALDO | CEK_MUTASI | LOGIN_MB | LOGIN_IB | LOGIN_ATM
    kode_channel        VARCHAR2(10)  NULL,       -- ATM | MOBILE | IB | TELLER | API
    nomor_referensi     VARCHAR2(50)  NULL,
    user_input          VARCHAR2(20)  NULL,
    terminal_input      VARCHAR2(19)  NULL,
    kode_cabang         VARCHAR2(10)  NULL,
    tanggal_input       TIMESTAMP     DEFAULT SYSTIMESTAMP,

    CONSTRAINT rekeningaktivitasnonfin_pkey PRIMARY KEY (id)
);

-- Index per rekening + tanggal (query audit)
CREATE INDEX idx_ran_norek_tgl
    ON ibankcore.rekeningaktivitasnonfin
    (nomor_rekening, tanggal_aktivitas DESC);

-- Index untuk monitoring per jenis/kode_channel
CREATE INDEX idx_ran_jenis
    ON ibankcore.rekeningaktivitasnonfin
    (kode_aktivitas, tanggal_aktivitas);

-- Index untuk purge / archival berkala
CREATE INDEX idx_ran_tglakt
    ON ibankcore.rekeningaktivitasnonfin
    (tanggal_aktivitas);

-- tambah kolom rekeningliabilitas
ALTER TABLE ibankcore.rekeningliabilitas
  ADD tgl_aktivitas_terakhir TIMESTAMP NULL;

ALTER TABLE ibankcore.rekeningliabilitas
  ADD tgl_aktivitas_nonfin_terakhir TIMESTAMP NULL;


-- tambah table temporary candidate tgl transaksi terakhir
CREATE TABLE ibanktmp.rekening_transaksi_terakhir (
    nomor_rekening      VARCHAR2(20)  NOT NULL,
    tanggal_transaksi   TIMESTAMP     NOT NULL,
    CONSTRAINT rekening_transaksi_terakhir_pkey PRIMARY KEY (nomor_rekening)
);

-- tambah table temporary candidate tgl aktivitas terakhir
CREATE TABLE ibanktmp.rekening_aktivitas_nonfin_terakhir (
    nomor_rekening      VARCHAR2(20)  NOT NULL,
    tanggal_aktivitas   TIMESTAMP     NOT NULL,
    CONSTRAINT rekening_aktivitas_terakhir_pkey PRIMARY KEY (nomor_rekening)
);

-- tambah script EOD hitung transaksi terakhir
INSERT INTO ibankent.bpscript (script_id, description, script_path, kode_aplikasi)
VALUES (ibankent.seq_bpscript.nextval, 'UPDATE ACCOUNT LAST TRX DATE', 'batchprocess\update_account_lasttxdate', '20000');

INSERT INTO ibankent.bpstep (step_id, description, step_order, disabled, scenario_code, script_id)
SELECT ibankent.seq_bpstep.nextval, description, 145, 'F', 'EOD01', script_id FROM ibankent.bpscript
WHERE script_path ='batchprocess\update_account_lasttxdate' AND kode_aplikasi='20000';

ALTER TABLE ibankcore.parametertransaksiumum
  ADD is_exclude_aktivitas_nasabah VARCHAR2(1) DEFAULT 'F';

-- Update kode transaksi sistem yang perlu di-exclude
UPDATE ibankcore.parametertransaksiumum
SET is_exclude_aktivitas_nasabah = 'T'
WHERE kode_transaksi IN ('SD', 'PD', 'SC', 'SCD', 'SDP', 'SDZ', 'SI');



-- Update table report rekening dormant
ALTER TABLE ibankrep.rekening_dorman
    ADD tgl_aktivitas_terakhir TIMESTAMP NULL;

-- Update table report rekening tidak aktif
CREATE TABLE ibankrep.rekening_tidak_aktif (
    id_report              NUMBER(*,0)     NOT NULL,
    nomor_rekening         VARCHAR2(20)    NOT NULL,
    tanggal_proses         DATE            NOT NULL,
    tgl_aktivitas_terakhir TIMESTAMP       NULL,
    saldo                  NUMBER(36, 10)  NULL,

    CONSTRAINT rekening_tidak_aktif_pkey PRIMARY KEY (id_report)
);

CREATE SEQUENCE ibankrep.seq_rekening_tidak_aktif
    START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCYCLE CACHE 20;

CREATE INDEX idx_rep_tdkakt_norek ON ibankrep.rekening_tidak_aktif
    (nomor_rekening, tanggal_proses DESC);

ALTER TABLE ibankcore.parameterglobal
  ADD kode_group VARCHAR2(30) NULL;

INSERT ALL
  INTO ibankcore.parameterglobal (kode_parameter, tipe_parameter, nilai_parameter, deskripsi, is_parameter_system, kode_group)
    VALUES ('TAKT_HARI',      'N', 360,   'Hari default jadi tidak aktif',       'T', 'REKENING_DORMANT')
  INTO ibankcore.parameterglobal (kode_parameter, tipe_parameter, nilai_parameter, deskripsi, is_parameter_system, kode_group)
    VALUES ('DORM_HARI',      'N', 1800,  'Hari default jadi dormant',           'T', 'REKENING_DORMANT')
  INTO ibankcore.parameterglobal (kode_parameter, tipe_parameter, nilai_parameter, deskripsi, is_parameter_system, kode_group)
    VALUES ('TUTUP_NOL_HARI', 'N', 730,   'Hari default tutup otomatis dormant', 'T', 'REKENING_DORMANT')
  INTO ibankcore.parameterglobal (kode_parameter, tipe_parameter, nilai_parameter, deskripsi, is_parameter_system, kode_group)
    VALUES ('TAKT_BIAYA',     'N', 0,     'Biaya default rekening tidak aktif',  'T', 'REKENING_DORMANT')
  INTO ibankcore.parameterglobal (kode_parameter, tipe_parameter, nilai_parameter, deskripsi, is_parameter_system, kode_group)
    VALUES ('DORM_BIAYA',     'N', 10000, 'Biaya default rekening dormant',      'T', 'REKENING_DORMANT')
SELECT 1 FROM DUAL;


ALTER TABLE ibankcore.produk ADD (
  is_custom_tidak_aktif         VARCHAR2(1),
  is_custom_dormant             VARCHAR2(1),
  is_custom_tutup_oto           VARCHAR2(1),
  jumlah_hari_jadi_dormant      NUMBER,
  biaya_rekening_tidak_aktif    NUMBER(20, 8),
  is_biaya_rekening_tidak_aktif VARCHAR2(1),
  is_exc_tidakaktif varchar2(1),
  is_exc_tutupnol varchar2(1)
);

CREATE TABLE ibanktmp.autoclose_zerobalance_candidate
(
   Nomor_Rekening varchar2(20) primary key
   , kode_cabang varchar2(20)
   , kode_valuta varchar2(10)
   , kode_produk varchar2(10)
   , param_hari_tutup_oto number
   , tgl_saldo_nol timestamp
   , saldo number(38, 8) 
);

CREATE INDEX idx_autoclose_cand_norek ON ibanktmp.autoclose_zerobalance_candidate(nomor_rekening);
CREATE INDEX idx_autoclose_cand_tgl ON ibanktmp.autoclose_zerobalance_candidate(tgl_saldo_nol);

CREATE TABLE IBANKTMP.rekening_dorman_candidate
(
      NOMOR_REKENING                  VARCHAR2(20)
    , SALDO                           NUMBER(36,10)
    , tgl_aktivitas_terakhir       TIMESTAMP(6)
    , kode_produk                     VARCHAR2(10)
    , param_hari_dormant        NUMBER
    , PROCESS_STATUS                  NUMBER
    , PRIMARY KEY (NOMOR_REKENING)
);

CREATE TABLE IBANKTMP.rekening_tidak_aktif_candidate
(
      NOMOR_REKENING                  VARCHAR2(20)
    , SALDO                           NUMBER(36,10)
    , tgl_aktivitas_terakhir       TIMESTAMP(6)
    , kode_produk                     VARCHAR2(10)
    , param_hari_tidak_aktif    NUMBER
    , PROCESS_STATUS                  NUMBER
    , PRIMARY KEY (NOMOR_REKENING)
);
