name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - dev

permissions:
  contents: write

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - run: pip install mkdocs mkdocs-material mkdocs-redirects

      - run: mkdocs gh-deploy --force
